name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_TOKEN }}
          yarn
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true
          USE_FIREBASE: true
          VUE_APP_FIRABASE_API_KEY: ${{ secrets.VUE_APP_FIRABASE_API_KEY }}
          VUE_APP_FIRABASE_MSG_SENDER_ID: ${{ secrets.VUE_APP_FIRABASE_MSG_SENDER_ID }}
          VUE_APP_FIRABASE_API_ID: ${{ secrets.VUE_APP_FIRABASE_API_ID }}

      - name: Deploy to Firebase
        run: yarn deploy
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
